### ISSUE TITLE
Add ES6 module 

### ISSUE THREAD

**Issue by sntran** [cferdinandi/tabby#109]
I have been using ES6 modules in browser. It would be nice if Tabby is written as ES6 module so I could `import` into my main module to use.

Example usage:

index.html
```html
<script type="module" src="/js/app.mjs"></script>
```

app.mjs
```mjs
import Tabby from "../node_modules/tabbyjs/dist/tabby.esm.js";

const tabs = new Tabby(`[data-tabs]`);
```

**Comment by cferdinandi** [comment]
This would require a rewrite of Tabby, and I'm not keen on doing that at this time. Additionally, many of my users still load this the old fashioned way with a `script` element (myself included), so that would need to be preserved as well.

Doing so would involve adding another build layer to create separate files for the different approaches, and as free software that I maintain in my spare time, I'm not ready to make that kind of commitment yet.

Sorry! :(

**Comment by sntran** [comment]
Would you take a PR for this then?

**Comment by cferdinandi** [comment]
I'm not sure how substantial the changes to the code base would have to be. Even with a PR, I'm ultimately on the hook to maintain it.

**Comment by mrleblanc101** [comment]
I was able to do `import Tabby from 'tabbyjs';` without issue.
