### ISSUE TITLE
CSS class for active tab missing

### ISSUE THREAD

**Issue by leolux** [cferdinandi/tabby#42]
I would like to style the active tab different from other tabs. How to do this?

**Comment by cferdinandi** [comment]
Not missing, just deliberately omitted. Tabby is "ugly on purpose" so that you can style it to your liking.

You could target `.tabs .active`, `.tabs button.active`, `.tabs li.active` or `.tabs a.active` depending on your setup and desired appearance. There's a million different ways you could configure the appearance, so I don't want to get too prescriptive.

**Comment by leolux** [comment]
Ok, thanks!

In the meanwhile I found out that the CSS class "active" gets already added to the corresponding tab by your javascript code. This means I have full flexibility in styling my tabs. That is awesome ;-)

**Comment by cferdinandi** [comment]
Oh sorry, yes. I should have mentioned that!
