### ISSUE TITLE
Hiding browser tooltips for hash urls

### ISSUE THREAD

**Issue by jaukia** [cferdinandi/tabby#52]
Thanks for the excellent library! 

I wonder if there is a way to hide the browser hover tooltips when using tabby, maybe by using something else that hash urls for navigation. Especially in mobile-like footer navigation, the flashing tooltips are more annoying than useful.

![screen shot 2016-03-30 at 14 28 16](https://cloud.githubusercontent.com/assets/270490/14140798/d98958b0-f683-11e5-98c1-4773f46106ec.png)
![screen shot 2016-03-30 at 14 29 15](https://cloud.githubusercontent.com/assets/270490/14140797/d9871104-f683-11e5-9d1b-2f54078fa3da.png)

**Comment by cferdinandi** [comment]
Hi there! Version 9 and lower used a different approach, data attributes, instead of hash URLs for the navigation. You can download it and check out the full docs here: https://github.com/cferdinandi/tabby/tree/v9.1.0

I switched over to the current setup for better accessibility, and strongly recommend sticking with it, but v9 and below definitely still work if it really bothers you.
