### ISSUE TITLE
Unable to view canvas when switching back to its tab

### ISSUE THREAD

**Issue by NetOperatorWibby** [cferdinandi/tabby#85]
I'm using Chart.js to display data and it uses `<canvas>` to display that data. My charts are in the initial tab of my app but when looking at another tab for a couple minutes, the charts disappear when going back to their tab.

I'd like to prevent this from happening. In my research, it appears that the canvas "forgets" what its dimensions are when the parent container is hidden. Is there some sort of fix I can apply to `tabby` to make my charts appear as normal?

**Comment by cferdinandi** [comment]
It's worth mentioning up front: Tabby doesn't actually set the hidden tabs to `display: hidden`, instead relying on a more accessible clipping technique to visually mask the content while keeping it in the DOM.

This feels like an issue with Chart.js rather than Tabby. Perhaps you can use the `callback` ([details](https://github.com/cferdinandi/tabby#global-settings)) to reinitialize your chart when the tab is brought back into view?

**Comment by NetOperatorWibby** [comment]
Oh I know it doesn't use `display` to hide, I've used this plugin for years (it's the best of its kind). Still, thanks for the callback idea, that might do the trick.
